# Generated by Django 2.2.5 on 2019-09-05 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profimg',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='images/about.jpg', upload_to='userprofile/'),
        ),
    ]
