# Generated by Django 2.2.5 on 2019-09-09 05:44

from django.db import migrations, models
import myapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20190905_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='images/about.jpg', upload_to='userprofile/', validators=[myapp.validators.validate_file_size]),
        ),
    ]
