# Generated by Django 2.2.5 on 2019-09-09 07:42

from django.db import migrations, models
import myapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20190909_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='images/about.png', upload_to='images/', validators=[myapp.validators.validate_file_size, myapp.validators.validation_file_extension]),
        ),
    ]
